# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run Python installer
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile merger.py
    - name: Upload linux artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: merger-linux
        # Directory containing files to upload
        path: dist
